language: java
jdk:
    - oraclejdk7
    - oraclejdk8
    - openjdk6
    - openjdk7
#before_install:
#    - sudo apt-get update -qq
#    - sudo apt-get install -qq gnupg
install: mvn install -Dgpg.skip=true -DskipTests=true
script: mvn test -Dgpg.skip=true